env:
  global:
    # DOCKER_EMAIL
    - secure: "gWl4/qlzONL2Iqnb4viKZ1a6OzGsrY8f5VxemaAaCEuEfkQio+H84jHIoNWoE0+acTq2yYWfRnIeNy1UTLqUqPqnJKUEUF6a6xb20vqnMwDK+jxiPO8yb4uI6UyTW2plApTWYp2LznZUa9TR0/ryWRm2Akq0qXQTEZvoSGD8y++aLB1CzUN3PnU64mZRBq9Rh0OFp+Oo3qTZx7+e4OqwFSAtxbQWd2on3nLBuPVE44JfM+Vb2HB/9bT67lJwYpsA8WY0T66lvUAzmGncAWyiJQXrJ2MEdO/LxoK9d/LeCxcgpwtgtmgcQ6z7i+A+xwWtRUV3BA8hGidsHmTBpiH9WioKBNiq4SJJ9srg0w2WwpjHQElhli36aKpL20Uamme5dKMSQc7020g+Kk868n7EEW0aYC/LJMvx4zOLVHLSN4hpLTp6/LsXg9ajZgfxZmjbLLkkXWxSsRBuo20YHlQPogm4M2rT+YqqzzVnwbZeOzIHDBqkm6TcFR9WBGGAZ7Md8w5OxaHBO7wZ0u9aTbKlPPqGV8es06Cbs9xlAFFh4p2k7+GanHo4KWf8u2ZXz3BFjEcK0RPvh6tVGo1QqP5HC/hwZAnT7tZatGJjhM7MsCTlD3S04XL5eXLatgvcihrBjCJnlEzLP/es2jiwlvwgx7ZjFUK+eUGoBSpqacW0XNQ="
     # DOCKER_USER
    - secure: "lmZHGEQabytvt+7QC5IbSKxg5KWrfxpGotk47Za6xtjpquqM+m0+TqqhZrqOUbAm3vHlvW9raF5rvbESv270ruMqIf9nWCwPvtbWVJAgyv//ExGpI6JvFvXveGvjxNuyiymZpgtXHakZPuG8A8l4iLmpH7iRI8HVVx5aIjHsRIbsPH5tfAnbpM5UPr1+iM9vpl6pjZ8bbI1tyk/bK7nAuQYZ8t2348AFcb9XLMzxhX0bA/jgcs0JaPZ5V+evvY75HGaBB2vP1kduI9p0Zrc/Uswin9OvhmInb1APdHynSsIGpf4Kb4ve9YrLqjProqTFUX3RFXD9V8UaB0M7l/44odyhk0r745Hzg2VP4uOHp5xG8nCZYTD6boV7r1qnOBU36Bu7BVjwMHDiEUcruHhV7aSdzTRb5hfTxfs7of6AHx+dHXwZiy8dkKmsNTJ0OxZeUnbOdH9D2tGCSRKBc1cCThC2Ojl7Z5k5IRtoKpM4N8gzIhvzbsf4NwZpoOoOMs5v0cZAyKLWfbJjrc45p3lKn9aVMka7rrn3KKO7OSnPVZg3kAz+bX3KyGmG+Dz94u4XARPMOSo16SeOMFyvq6G4pCKjOchUHhgx521Sovq7T9bcDYC3eN0GK4BAsJW1lHSBBkOXJnrcBCXORGwykqw+lHrlENz6d6tKy1hbG3qgmas="
    # DOCKER_PASS
    - secure: "T5XjFdDE02AUnrzIXJvCFvk75xhM1zNqciivLsPpB9yrM0JU3GhID0aPm8/8jEP4xexSbKuHIXUP4BpBQuxq8ei6jh28GxN/kA0XnrDiYGWPW2V79z+Q/8D1P5Iy2vpTzSMjQNuUczgYS+EHq1a3u7FH0w5ebcCPeZ+6PRyMaMsRMLuJBGIh+0a6mumCRNZ05ZPZno2q8K/lvXoXjLXvpV9HFNtSfTtZLHQyLr1S7LuYsTI9BTyTQHYofXm9NvBSWadUDv18yOK64Iccr2xEs7RgelNfg+U72C8mZD3cirIQilChLy2JfZaKPqC0e883NogNtX1tFn0Mm5J7SaoT+X8JztnLNIdVO80CdO6jHELaiSzaNMMoep4WwPJKmCusmo2Z6cSjAhNwKrlkOKsg/jvSFCtNV7oLHPJSwM5xmYBSxNHamvIunUffhJNK3t2iiS8BYM/MO7XGgil3J24klbExGG8zzYRtzpvciMuSxBcnsqmVb0WW3Eng9PycERTDpxSA9L281TfV1088r3fjdN+6Sk9ePVvL4vyNqZPu6Mj7gUK87eqotCTXhvGI+uqWFuzsTxI6hBTCbUdoh2G1cWvW2TPyO+op8Hn4LjLqIoHMy2Zq2s/q6A6835mutLNlj11NpvEBPKvDHXXE4FnU3qqVOmeqGQFLTJbtotJwklM="

language: java

jdk:
- oraclejdk8

services:
  - docker

before_install:
- chmod +x gradlew

notifications:
  email: false

deploy:
  - provider: releases
    api_key:
      secure: NPQy7UMCgXXXhBK1tZ/X/bV3pFkhe6H7i5qJC4UNqj9Ry4fgXSMqWT/mNkflzIagVS74sMP6vO9f+zJrR9//fhyFBDV8RJJF7hJ6aj3Dy7LZ+cs/tG8D5xdkz1002+UpwaPVc4+HxaS0b8D+b8gIWhdGfr30oqZoWM6xWRSg/S5/ebvZp2TV0lE1x8Bim9ATju4N08oQCaR52gn+2MOePGrDExNsKSjXh2c5aTYt7s3SHF9MisbCoTMxOEg2fwgRLt69DxIt6SSYbj1dqxAw78mg1nndMjXHdgRrXRrQiLKizdJZyodYqOjn7lPiU7mgCrFWCKk2/W9bzKBoI0kVOwh4Z/IJAP7RGUpT5HFw7XWiWmuMWILqSeUR1mEs9NFG7ObCbeE6c7oc9nso+vCWiql9aOH6MXtJypfy/nzeO+hbsh1ilnReIKPg2tIwPhGOHR0Y5fO2iTIuVIn62fBP0Tkxq3Sp6qFRVb0bXHvVgLYYHhbKFDSWrgS8iTC2WQ3IoCwuT1y0XyRAutE2EoeYmvSlAJbDAZFSVJcq/89y1eggWsP1DMemWpU2gGy8jqj8Dv+EF2gKsO6bgAgXunX7zZ4sK0gnTDFlJ6c2tmeEKZV2WSbiFzWr7my1MAmDT0m5dmJE9NvKr/pGGFN9HuStLU3MVPMMB83OEDMezV3VrAo=
    file: build/libs/fake-smtp-server-$TRAVIS_TAG.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy-to-docker.sh
    skip_cleanup: true
    on:
      tags: true