env:
  global:
    # DOCKER_EMAIL
    - secure: "gWl4/qlzONL2Iqnb4viKZ1a6OzGsrY8f5VxemaAaCEuEfkQio+H84jHIoNWoE0+acTq2yYWfRnIeNy1UTLqUqPqnJKUEUF6a6xb20vqnMwDK+jxiPO8yb4uI6UyTW2plApTWYp2LznZUa9TR0/ryWRm2Akq0qXQTEZvoSGD8y++aLB1CzUN3PnU64mZRBq9Rh0OFp+Oo3qTZx7+e4OqwFSAtxbQWd2on3nLBuPVE44JfM+Vb2HB/9bT67lJwYpsA8WY0T66lvUAzmGncAWyiJQXrJ2MEdO/LxoK9d/LeCxcgpwtgtmgcQ6z7i+A+xwWtRUV3BA8hGidsHmTBpiH9WioKBNiq4SJJ9srg0w2WwpjHQElhli36aKpL20Uamme5dKMSQc7020g+Kk868n7EEW0aYC/LJMvx4zOLVHLSN4hpLTp6/LsXg9ajZgfxZmjbLLkkXWxSsRBuo20YHlQPogm4M2rT+YqqzzVnwbZeOzIHDBqkm6TcFR9WBGGAZ7Md8w5OxaHBO7wZ0u9aTbKlPPqGV8es06Cbs9xlAFFh4p2k7+GanHo4KWf8u2ZXz3BFjEcK0RPvh6tVGo1QqP5HC/hwZAnT7tZatGJjhM7MsCTlD3S04XL5eXLatgvcihrBjCJnlEzLP/es2jiwlvwgx7ZjFUK+eUGoBSpqacW0XNQ="
     # DOCKER_USER
    - secure: "lmZHGEQabytvt+7QC5IbSKxg5KWrfxpGotk47Za6xtjpquqM+m0+TqqhZrqOUbAm3vHlvW9raF5rvbESv270ruMqIf9nWCwPvtbWVJAgyv//ExGpI6JvFvXveGvjxNuyiymZpgtXHakZPuG8A8l4iLmpH7iRI8HVVx5aIjHsRIbsPH5tfAnbpM5UPr1+iM9vpl6pjZ8bbI1tyk/bK7nAuQYZ8t2348AFcb9XLMzxhX0bA/jgcs0JaPZ5V+evvY75HGaBB2vP1kduI9p0Zrc/Uswin9OvhmInb1APdHynSsIGpf4Kb4ve9YrLqjProqTFUX3RFXD9V8UaB0M7l/44odyhk0r745Hzg2VP4uOHp5xG8nCZYTD6boV7r1qnOBU36Bu7BVjwMHDiEUcruHhV7aSdzTRb5hfTxfs7of6AHx+dHXwZiy8dkKmsNTJ0OxZeUnbOdH9D2tGCSRKBc1cCThC2Ojl7Z5k5IRtoKpM4N8gzIhvzbsf4NwZpoOoOMs5v0cZAyKLWfbJjrc45p3lKn9aVMka7rrn3KKO7OSnPVZg3kAz+bX3KyGmG+Dz94u4XARPMOSo16SeOMFyvq6G4pCKjOchUHhgx521Sovq7T9bcDYC3eN0GK4BAsJW1lHSBBkOXJnrcBCXORGwykqw+lHrlENz6d6tKy1hbG3qgmas="
    # DOCKER_PASS
    - secure: "kCpoX5hUBJlyMbdCu+gs/NXYOsjAYTARnzizB6vE2N4TgehmhhWmDtyBUk0bGvgWahHZvJKvODNGJsKNIvYdtg4bpxKLS7+pl2r/JXUxzFXNE0s88VmAk8vRbKktK8lFosbY4GHBpBgr2IA7xu6hKmnpEsgwmzGu607JHxDSAqCMc/QcujWtGfmmVHNPPAh8vrYkLBJcslMFuQ2YseHRE7Zv1RganzpECL2J0qo67Lopb0cjZcILnvocYCf711G5SBGt2W438LGhv0ogMosfHRMzxqiJwWnGtjQWhjWYFp+lJlhKrHvL8KMEVUXUeuk0LbCai+UO3iEhP+pOV7NJqRBQRO7icXCB5aE6Cf08NGk82MQIL3MYYCqy+QbF3rnsJ2CZ/iJXweq9U1ik55EOrXfGaHQ1yKk7kcwRHhYTAvik/triXaKjp00JXgtli0BpRNegA/9S8/W5zjgJJ0aGs0k2Gl6o97dyn7PZZBO5VQCNqruxCSuhsLzoKagyKXmtWIM3utO0cnraVsyLpGI8FfYYgU/vxfZXzrTaDPzgU2SVDy2YdYOzirer4iueHiEPby+l2HxCeO8yaG9A6oPEys1JW4l72ln/Lzl2hp71m42L1itWEBEELB65y/CSYoRsY+6RDmfcp4YxblKXIjeexgnrGJ6//yjtyNFpjF18tm8="

language: java

jdk:
- oraclejdk8

services:
  - docker

before_install:
- chmod +x gradlew

notifications:
  email: false

addons:
  sonarcloud:
    organization: "gessnerfl-github"
    token:
      secure: "mmHtKZvvtIC3Ggzn/ppgW+XtWz77DCwjV4kN28ZEMxddcCHMCw0kV7GNRt9AcVxWv6WIXEdFCHChIcVafpDCTBefunVPnanhYZhfXE5IYiy29UAbyArwXcB0EuioR07dANCIIfDelYpOGUh+/Lw2SkBot4uUGsmQFakSz4oZDxhJU8V6DPARaJSK8E7hBOPB/4kAazAkwoWSg6VcNk8vB2I5RxXXtEqWlvUAERE2yVNoQ17+eFWLhGp0yEfB+zBghq5nuFHj3tb79FyjM78sz2Y1vMx6EbnUl8qN8BY8YMtovOgg763Fai6hM/MJoODVSbYsHf/Wheq71Q1+vRaVEurfWw98iEJ0i+5pHCqL1fO/Lxck2jE+nO9SI2qjZ6RgHL/C7M9MUcOsXNLDmfZcFBdR756VWPO356A6AjUzRGo4DCXdyiNuC+NGYg2koOarzloUQSe07qb6EB3sYijbNQmBAxs2nNwXmGqwdrnD+pvqZPOFHHN6DGhg8q7ZVlAyTdaMbWJOlPXybcySGOkzHDPEDTpONppSNkp0kZREpgmk32GYCWSTt7WdKx+WrKzrS4ZxXgElWmJWiRHmrgxMVPft57XsRjxPyHnGmQYQ8x9LVlVy7dNm1Jr4vlxuq8xjhUpPeEvvyPMi4qRmy8HMKhy+HXEkFROqYP01X2l4UcE="
    branches:
      - master

deploy:
  - provider: releases
    api_key:
      secure: NPQy7UMCgXXXhBK1tZ/X/bV3pFkhe6H7i5qJC4UNqj9Ry4fgXSMqWT/mNkflzIagVS74sMP6vO9f+zJrR9//fhyFBDV8RJJF7hJ6aj3Dy7LZ+cs/tG8D5xdkz1002+UpwaPVc4+HxaS0b8D+b8gIWhdGfr30oqZoWM6xWRSg/S5/ebvZp2TV0lE1x8Bim9ATju4N08oQCaR52gn+2MOePGrDExNsKSjXh2c5aTYt7s3SHF9MisbCoTMxOEg2fwgRLt69DxIt6SSYbj1dqxAw78mg1nndMjXHdgRrXRrQiLKizdJZyodYqOjn7lPiU7mgCrFWCKk2/W9bzKBoI0kVOwh4Z/IJAP7RGUpT5HFw7XWiWmuMWILqSeUR1mEs9NFG7ObCbeE6c7oc9nso+vCWiql9aOH6MXtJypfy/nzeO+hbsh1ilnReIKPg2tIwPhGOHR0Y5fO2iTIuVIn62fBP0Tkxq3Sp6qFRVb0bXHvVgLYYHhbKFDSWrgS8iTC2WQ3IoCwuT1y0XyRAutE2EoeYmvSlAJbDAZFSVJcq/89y1eggWsP1DMemWpU2gGy8jqj8Dv+EF2gKsO6bgAgXunX7zZ4sK0gnTDFlJ6c2tmeEKZV2WSbiFzWr7my1MAmDT0m5dmJE9NvKr/pGGFN9HuStLU3MVPMMB83OEDMezV3VrAo=
    file: build/libs/fake-smtp-server-$TRAVIS_TAG.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy-to-docker.sh
    skip_cleanup: true
    on:
      tags: true